backend:
  name: git-gateway
  branch: main
media_folder: "public/Resources"
public_folder: "/Resources"
collections:
  - name: "projects_blog"
    label: "Projects"
    folder: "src/projects_blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Category", name: "category", widget: "string"}
collections:
  - name: "aboutus_text"
    label: "About Us Homepage"
    folder: "src/aboutus_text"
    create: false
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Description", name: "description", widget: "string"}
collections:
  - name: "service_description"
    label: "Services Detail"
    folder: "src/service_description"
    create: false
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Description", name: "description", widget: "string"}
collections:
  - name: "slidertext"
    label: "Slider Text Homepage"
    folder: "src/slidertext"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Text", name: "content", widget: "string"}
collections:
  - name: "aboutpage"
    label: "About Page"
    folder: "src/aboutpage"
    create: false
    slug: "{{slug}}"
    fields:
      - { label: "About the company", name: "companydesc", widget: "string"}
      - { label: "Jack's quote", name: "jackquote", widget: "string"}
      - { label: "Dani's quote", name: "daniquote", widget: "string"}